# for node.js 
version: 0.2
env:
#    variables:
#        S3_BUCKET: ”cf-templates-1kislut2dci3g-ap-southeast-2“
 phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing ...
#      - npm install -g mocha
      - pip install --user awscli
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
#      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
#      - echo Compiling the Node.js code
#      - mocha test.js
  post_build:
    commands:
#      - aws s3 sync dist s3://${S3_BUCKET} --delete"
      - echo Build completed on `date`
