version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10  
    commands:
      - echo Installing ...
#      - npm install -g aws-cli
#     - npm install express
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
